const userTypes = {

    EMAIL_SIGN_IGN_START : 'EMAIL_SIGN_IN_START',
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    RESET_PASSWORD_SUCCESS : 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR : ' RESET_PASSWORD_ERROR',
    RESET_AUTH_FORMS : 'RESET_AUTH_FORMS'
};
export default userTypes;